### ISSUE TITLE
Code cleanup

### ISSUE THREAD

**Issue by vm-wylbur** [hrodriguezri/DotFiles#1]
I just reviewed your dotfiles, and I think that you might want to check lines 24-28 in `bashrc`. I don't think you have install privileges on our server, so this command will fail if `tree` is not found. 

Also: what does `task` do? you might want to test it to see when it works and when it fails. Good luck!

**Comment by hrodriguezri** [comment]
Yes @vm-wylbur,

I just cleaned up the snippet code referred to `tree` because it was done to test if `tree `function was installed, but it is unnecessary now, `tree` is installed now. On the other hand, I kept `task` if it is likely to use later to create input, output and src directories recursively.  You can see the changes [here](https://github.com/hrodriguezri/DotFiles/blob/master/bash/bashrc).

**Comment by vm-wylbur** [comment]
ok. if you're happy with this result, please close this issue.
